name: My first workflow

on: push

jobs:
    fisrt_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@4.0

        - name: welcome message
          run: echo "My First Github Actions job"

        - name: list files
          run: ls -lart

        - name: Show the existing directory
          run: pwd

        - name: read files
          run: cat README.md