name: script testing workflows

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: list all the files
          run: ls -lart

        - name: Script based workflows
          run: ./ascii-script.sh