name: Docker image build & variable testing

on: push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: vivekpdgupta
    IMAGE_NAME: github-actions-nginx

######################## Normal way of passing the varibales ########################
#jobs:
#   runs-on: ubuntu-latest
#  steps:
#    - name: Docker build
#      run: docker build -t docker.io/dockerusername/imagename:latest
#   
#    - name: Docker login
#      run: docker login --username=dockerusername --password=s3cUrePaSsW0rd
#
#    - name: docker publish
#      run: docker push docker.io/dockerUsername/imageName:latest
#   
#   docker_image_deploy:
#    needs: docker_image_build
#    runs-on: ubuntu-latest
#    steps:
#    - name: Docker run
#      run: docker run -d -p 8080:80 docker.io/dockerusername/imageName:latest

################## exploring environment varibales at step level ############################

#jobs:
#   docker_image_build:
#    runs-on: ubuntu-latest
#     steps:
#     - name: Docker build
#       env:
#         CONTAINER_REGISTRY: 
#         DOCKER_USERNAME:
#         IMAGE_NAME: 
#       run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME
#     
#     - name: Docker login
#       env:
#         DOCKER_USERNAME:
#         DOCKER_PASSWORD:
#       run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
# 
#     - name: docker publish
#     env:
#         CONTAINER_REGISTRY:
#         DOCKER_USERNAME:
#         IMAGE_NAME:
#       run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME
#     
#    docker_image_deploy:
#     needs: docker_image_build
#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker run
#     env:
#         CONTAINER_REGISTRY:
#         DOCKER_USERNAME:
#         IMAGE_NAME:
#       run: docker run -d -p 8080:80 docker.io/dockerusername/imageName:latest

######## exploring environment varibales at Job level & adding password into varibale ###########
jobs:
   docker_image_build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker build
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME}}:latest 
    
    - name: Docker login
      env:
        DOCKER_PASSWORD: Vivek@12345
      run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    - name: docker publish
      run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
    
   docker_image_deploy:
    needs: docker_image_build
    runs-on: ubuntu-latest
    steps:
    - name: Docker run
      run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest